//! What the newest published release is, and what changed in it.
//!
//! An old binary cannot know about a release that came after it, so this is
//! fetched rather than compiled in. The version is the release tag; the change
//! line is the first line of the release body, which is hand-written per release
//! precisely so it reads like something a person would say.
//!
//! The fetch never happens on the handoff path. It refreshes once in the
//! background when the server starts, writes a cache, and the handoff only ever
//! reads that cache. A version check must never delay a tool call.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

const RELEASES_LATEST: &str = "https://api.github.com/repos/repotracer/repotracer/releases/latest";
const REFRESH_INTERVAL: Duration = Duration::from_secs(24 * 60 * 60);
const FETCH_TIMEOUT: Duration = Duration::from_secs(5);
/// Keeps the change line from ever dominating the handoff.
const MAX_CHANGE_LEN: usize = 120;

#[derive(Serialize, Deserialize, Default, Clone)]
pub struct Cached {
    pub checked_unix: u64,
    pub version: String,
    pub change: String,
}

fn home() -> Option<PathBuf> {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
}

fn cache_path() -> Option<PathBuf> {
    home().map(|h| h.join(".repotracer").join("latest-release.json"))
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn disabled() -> bool {
    matches!(
        std::env::var("REPOTRACER_NO_UPDATE_CHECK").as_deref(),
        Ok("1") | Ok("true")
    )
}

fn read_cache() -> Option<Cached> {
    let text = std::fs::read_to_string(cache_path()?).ok()?;
    serde_json::from_str(&text).ok()
}

/// The release to advertise, if the running binary is behind it.
///
/// Reads only the cache, so this is a file read and never a network call.
pub fn pending_update(running: &str, config_allows: bool) -> Option<(String, String)> {
    if !config_allows || disabled() {
        return None;
    }
    let cached = read_cache()?;
    if cached.version.is_empty() || !is_newer(&cached.version, running) {
        return None;
    }
    Some((cached.version, cached.change))
}

/// Refresh the cache in the background if it is stale. Called once at startup.
///
/// Failure is silent by design: an unreachable release feed is not the user's
/// problem and must not surface as an error during a coding session.
pub fn refresh_in_background(config_allows: bool) {
    if !config_allows || disabled() {
        return;
    }
    let fresh = read_cache()
        .map(|c| now_unix().saturating_sub(c.checked_unix) < REFRESH_INTERVAL.as_secs())
        .unwrap_or(false);
    if fresh {
        return;
    }
    tokio::spawn(async {
        if let Some(cached) = fetch().await {
            if let Some(path) = cache_path() {
                if let Some(parent) = path.parent() {
                    let _ = std::fs::create_dir_all(parent);
                }
                if let Ok(text) = serde_json::to_string(&cached) {
                    let _ = std::fs::write(path, text);
                }
            }
        }
    });
}

async fn fetch() -> Option<Cached> {
    let client = reqwest::Client::builder()
        .timeout(FETCH_TIMEOUT)
        .user_agent(concat!("repotracer/", env!("CARGO_PKG_VERSION")))
        .build()
        .ok()?;
    let body: serde_json::Value = client
        .get(RELEASES_LATEST)
        .send()
        .await
        .ok()?
        .json()
        .await
        .ok()?;
    let version = body
        .get("tag_name")?
        .as_str()?
        .trim_start_matches('v')
        .to_string();
    let change = body
        .get("body")
        .and_then(|b| b.as_str())
        .map(summarise_change)
        .unwrap_or_default();
    Some(Cached {
        checked_unix: now_unix(),
        version,
        change,
    })
}

/// Take the hand-written headline from a release body: the first line that is
/// actual prose, not a heading, bullet, or autogenerated section.
fn summarise_change(body: &str) -> String {
    let line = body
        .lines()
        .map(str::trim)
        .find(|l| {
            !l.is_empty()
                && !l.starts_with('#')
                && !l.starts_with('*')
                && !l.starts_with('-')
                && !l.starts_with("**")
                && !l.starts_with("What's Changed")
        })
        .unwrap_or_default();

    let mut change = line.trim_end_matches('.').to_string();
    if change.len() > MAX_CHANGE_LEN {
        change.truncate(MAX_CHANGE_LEN);
        while !change.is_char_boundary(change.len()) {
            change.pop();
        }
        change.push('…');
    }
    change
}

/// Compare dotted numeric versions. Anything unparsable sorts as older, so a
/// malformed tag can never nag the user to upgrade.
fn is_newer(candidate: &str, current: &str) -> bool {
    fn parts(v: &str) -> Vec<u64> {
        v.trim_start_matches('v')
            .split('.')
            .map(|p| {
                p.chars()
                    .take_while(char::is_ascii_digit)
                    .collect::<String>()
                    .parse()
                    .unwrap_or(0)
            })
            .collect()
    }
    let (a, b) = (parts(candidate), parts(current));
    for index in 0..a.len().max(b.len()) {
        let (x, y) = (
            a.get(index).copied().unwrap_or(0),
            b.get(index).copied().unwrap_or(0),
        );
        if x != y {
            return x > y;
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_config_switch_silences_it() {
        assert!(pending_update("0.0.1", false).is_none());
    }

    #[test]
    fn version_comparison_handles_the_shapes_we_publish() {
        assert!(is_newer("0.1.9", "0.1.3"));
        assert!(is_newer("v0.2.0", "0.1.9"));
        assert!(is_newer("1.0.0", "0.9.9"));
        assert!(!is_newer("0.1.3", "0.1.3"));
        assert!(!is_newer("0.1.2", "0.1.3"));
        // A malformed tag must never nag the user to upgrade.
        assert!(!is_newer("garbage", "0.1.3"));
        assert!(!is_newer("", "0.1.3"));
    }

    #[test]
    fn change_line_takes_the_hand_written_prose() {
        let body = "## What's Changed\n\n\
                    Setup no longer scans the working directory.\n\n\
                    * chore: bump deps by @someone\n";
        assert_eq!(
            summarise_change(body),
            "Setup no longer scans the working directory"
        );
    }

    #[test]
    fn change_line_survives_an_autogenerated_body() {
        // GitHub's generated notes are all headings and bullets; better to say
        // nothing than to relay "* chore: bump deps by @someone".
        let body = "## What's Changed\n* chore: bump deps by @someone\n* fix: thing by @other\n";
        assert_eq!(summarise_change(body), "");
    }

    #[test]
    fn change_line_is_bounded() {
        let body = "x".repeat(400);
        let change = summarise_change(&body);
        assert!(change.chars().count() <= MAX_CHANGE_LEN + 1);
        assert!(change.ends_with('…'));
    }
}
